### ISSUE TITLE
Getting an error while trying to build

### ISSUE THREAD

**Issue by snshn** [jonof/jftekwar#2]
Hello.

Platform: Debian GNU/Linux 8
Output: `make: *** No rule to make target 'src/game_icon.o', needed by 'tekwar'.  Stop.`

May I ask how complete this project is? E.g. will it be possible for me to play the game?
I see that the missing object can be build within your port of Duke Nukem 3D, but I assume the icon may be not the only thing that's missing from this port?

Thank you.

**Comment by jonof** [comment]
Should work now, for `make tekwar` at least. I haven't got the editor fixed yet.
