### ISSUE TITLE
After video the game exits

### ISSUE THREAD

**Issue by orderorder** [jonof/jftekwar#4]
tekloadsetup...
 initgroupfile...
 inittimer...
Initialising timer
 tekinitmultiplayers...
 loadpics...
loadpics(): Invalid art file version in tiles012.art
 tekpreinit...
 tekgamestarted...
 initinput...
No game controllers found
 initmouse...
Setting video mode 640x480 (8-bpp windowed)
 initsb...
SDL_GetCurrentAudioDriver: pulseaudio
Cachesize: 0
Newhandle: 0x0x55ad0bb56458, Newbytes: 2656, *Newlock: 200
Cachesize = 0
Cacnum = 0
Cache length sum = 0
ERROR: BUFFER TOO BIG TO FIT IN CACHE!

**Comment by jonof** [comment]
> loadpics(): Invalid art file version in tiles012.art

That looks to be the problem. You've got damaged content. Compare with the sizes/checksums I've attached read from the original CD.

[hashes.txt](https://github.com/jonof/jftekwar/files/10327315/hashes.txt)

**Comment by orderorder** [comment]
Good, now it works, thank you. Do you have in mind to support tracks in .ogg format? Or the possibility of combining mouse and keyboard like in modern shooters?

**Comment by jonof** [comment]
We'll see how bored I am next Christmas. :-)
